# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.test_custom_rule_input_scan import TestCustomRuleInputScan  # noqa: E501
from swagger_client.rest import ApiException


class TestTestCustomRuleInputScan(unittest.TestCase):
    """TestCustomRuleInputScan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCustomRuleInputScan(self):
        """Test TestCustomRuleInputScan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_custom_rule_input_scan.TestCustomRuleInputScan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
