# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cors_api import CORSApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCORSApi(unittest.TestCase):
    """CORSApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cors_api.CORSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rules_options(self):
        """Test case for rules_options

        CORS support.  # noqa: E501
        """
        pass

    def test_rules_rule_id_options(self):
        """Test case for rules_rule_id_options

        CORS support.  # noqa: E501
        """
        pass

    def test_rules_test_input_options(self):
        """Test case for rules_test_input_options

        CORS support.  # noqa: E501
        """
        pass

    def test_rules_test_options(self):
        """Test case for rules_test_options

        CORS support.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
