# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scans_api import ScansApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScansApi(unittest.TestCase):
    """ScansApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.scans_api.ScansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_scan(self):
        """Test case for create_scan

        Creates and triggers a new environment scan.  # noqa: E501
        """
        pass

    def test_get_compliance_by_resource_types(self):
        """Test case for get_compliance_by_resource_types

        Lists compliance results by resource type for a scan.  # noqa: E501
        """
        pass

    def test_get_compliance_by_rules(self):
        """Test case for get_compliance_by_rules

        Lists compliance results by rule for a scan.  # noqa: E501
        """
        pass

    def test_get_scan(self):
        """Test case for get_scan

        Retrieves details for a scan.  # noqa: E501
        """
        pass

    def test_list_scans(self):
        """Test case for list_scans

        Lists scans for an environment.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
