# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.metadata_api import MetadataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.metadata_api.MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policy(self):
        """Test case for create_policy

        Returns the permissions required to survey and remediate resources.  # noqa: E501
        """
        pass

    def test_get_resource_types(self):
        """Test case for get_resource_types

        Lists the resource types supported by Fugue.  # noqa: E501
        """
        pass

    def test_get_swagger(self):
        """Test case for get_swagger

        Returns the OpenAPI 2.0 specification for this API.  # noqa: E501
        """
        pass

    def test_get_swagger_ui(self):
        """Test case for get_swagger_ui

        Returns a friendly user interface for the OpenAPI 2.0 specification for this API.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
