# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.compliance_diff_rules import ComplianceDiffRules  # noqa: E501
from swagger_client.rest import ApiException


class TestComplianceDiffRules(unittest.TestCase):
    """ComplianceDiffRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplianceDiffRules(self):
        """Test ComplianceDiffRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.compliance_diff_rules.ComplianceDiffRules()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
