# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scan_with_summary import ScanWithSummary  # noqa: E501
from swagger_client.rest import ApiException


class TestScanWithSummary(unittest.TestCase):
    """ScanWithSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScanWithSummary(self):
        """Test ScanWithSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scan_with_summary.ScanWithSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
