# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_rules_api import CustomRulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomRulesApi(unittest.TestCase):
    """CustomRulesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_rules_api.CustomRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_custom_rule(self):
        """Test case for create_custom_rule

        Create a new custom rule.  # noqa: E501
        """
        pass

    def test_delete_custom_rule(self):
        """Test case for delete_custom_rule

        Delete a custom rule.  # noqa: E501
        """
        pass

    def test_get_custom_rule(self):
        """Test case for get_custom_rule

        Get details on a single custom rule.  # noqa: E501
        """
        pass

    def test_list_custom_rules(self):
        """Test case for list_custom_rules

        List custom rules.  # noqa: E501
        """
        pass

    def test_test_custom_rule(self):
        """Test case for test_custom_rule

        Test a custom rule.  # noqa: E501
        """
        pass

    def test_test_custom_rule_input(self):
        """Test case for test_custom_rule_input

        Get the input for a custom rule test.  # noqa: E501
        """
        pass

    def test_update_custom_rule(self):
        """Test case for update_custom_rule

        Update custom rule.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
