# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.environments_api import EnvironmentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.environments_api.EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_environment(self):
        """Test case for create_environment

        Creates a new environment.  # noqa: E501
        """
        pass

    def test_delete_environment(self):
        """Test case for delete_environment

        Deletes an environment.  # noqa: E501
        """
        pass

    def test_get_environment(self):
        """Test case for get_environment

        Retrieves details and resource summary for an environment.  # noqa: E501
        """
        pass

    def test_list_environments(self):
        """Test case for list_environments

        Lists details for all environments.  # noqa: E501
        """
        pass

    def test_update_environment(self):
        """Test case for update_environment

        Updates an environment.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
