# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.non_compliant_resource import NonCompliantResource  # noqa: F401,E501


class ComplianceByResourceType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_type': 'str',
        'total': 'int',
        'compliant': 'int',
        'noncompliant': 'list[NonCompliantResource]'
    }

    attribute_map = {
        'resource_type': 'resource_type',
        'total': 'total',
        'compliant': 'compliant',
        'noncompliant': 'noncompliant'
    }

    def __init__(self, resource_type=None, total=None, compliant=None, noncompliant=None):  # noqa: E501
        """ComplianceByResourceType - a model defined in Swagger"""  # noqa: E501

        self._resource_type = None
        self._total = None
        self._compliant = None
        self._noncompliant = None
        self.discriminator = None

        if resource_type is not None:
            self.resource_type = resource_type
        if total is not None:
            self.total = total
        if compliant is not None:
            self.compliant = compliant
        if noncompliant is not None:
            self.noncompliant = noncompliant

    @property
    def resource_type(self):
        """Gets the resource_type of this ComplianceByResourceType.  # noqa: E501

        Name of the resource type.  # noqa: E501

        :return: The resource_type of this ComplianceByResourceType.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ComplianceByResourceType.

        Name of the resource type.  # noqa: E501

        :param resource_type: The resource_type of this ComplianceByResourceType.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def total(self):
        """Gets the total of this ComplianceByResourceType.  # noqa: E501

        Count of all resources evaluated for this resource type.  # noqa: E501

        :return: The total of this ComplianceByResourceType.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ComplianceByResourceType.

        Count of all resources evaluated for this resource type.  # noqa: E501

        :param total: The total of this ComplianceByResourceType.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def compliant(self):
        """Gets the compliant of this ComplianceByResourceType.  # noqa: E501

        Count of resources found to be fully compliant with all rules it has been evaulated against.  # noqa: E501

        :return: The compliant of this ComplianceByResourceType.  # noqa: E501
        :rtype: int
        """
        return self._compliant

    @compliant.setter
    def compliant(self, compliant):
        """Sets the compliant of this ComplianceByResourceType.

        Count of resources found to be fully compliant with all rules it has been evaulated against.  # noqa: E501

        :param compliant: The compliant of this ComplianceByResourceType.  # noqa: E501
        :type: int
        """

        self._compliant = compliant

    @property
    def noncompliant(self):
        """Gets the noncompliant of this ComplianceByResourceType.  # noqa: E501

        List of non-compliant resources and the rules they have violated.  # noqa: E501

        :return: The noncompliant of this ComplianceByResourceType.  # noqa: E501
        :rtype: list[NonCompliantResource]
        """
        return self._noncompliant

    @noncompliant.setter
    def noncompliant(self, noncompliant):
        """Sets the noncompliant of this ComplianceByResourceType.

        List of non-compliant resources and the rules they have violated.  # noqa: E501

        :param noncompliant: The noncompliant of this ComplianceByResourceType.  # noqa: E501
        :type: list[NonCompliantResource]
        """

        self._noncompliant = noncompliant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComplianceByResourceType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
