# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.provider_options import ProviderOptions  # noqa: F401,E501


class CreateEnvironmentInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'provider': 'str',
        'provider_options': 'ProviderOptions',
        'compliance_families': 'list[str]',
        'survey_resource_types': 'list[str]',
        'remediate_resource_types': 'list[str]',
        'scan_schedule_enabled': 'bool',
        'scan_interval': 'int'
    }

    attribute_map = {
        'name': 'name',
        'provider': 'provider',
        'provider_options': 'provider_options',
        'compliance_families': 'compliance_families',
        'survey_resource_types': 'survey_resource_types',
        'remediate_resource_types': 'remediate_resource_types',
        'scan_schedule_enabled': 'scan_schedule_enabled',
        'scan_interval': 'scan_interval'
    }

    def __init__(self, name=None, provider=None, provider_options=None, compliance_families=None, survey_resource_types=None, remediate_resource_types=None, scan_schedule_enabled=None, scan_interval=None):  # noqa: E501
        """CreateEnvironmentInput - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._provider = None
        self._provider_options = None
        self._compliance_families = None
        self._survey_resource_types = None
        self._remediate_resource_types = None
        self._scan_schedule_enabled = None
        self._scan_interval = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if provider is not None:
            self.provider = provider
        if provider_options is not None:
            self.provider_options = provider_options
        if compliance_families is not None:
            self.compliance_families = compliance_families
        if survey_resource_types is not None:
            self.survey_resource_types = survey_resource_types
        if remediate_resource_types is not None:
            self.remediate_resource_types = remediate_resource_types
        if scan_schedule_enabled is not None:
            self.scan_schedule_enabled = scan_schedule_enabled
        if scan_interval is not None:
            self.scan_interval = scan_interval

    @property
    def name(self):
        """Gets the name of this CreateEnvironmentInput.  # noqa: E501

        Name of the environment.  # noqa: E501

        :return: The name of this CreateEnvironmentInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateEnvironmentInput.

        Name of the environment.  # noqa: E501

        :param name: The name of this CreateEnvironmentInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def provider(self):
        """Gets the provider of this CreateEnvironmentInput.  # noqa: E501

        Name of the cloud service provider for the environment.  # noqa: E501

        :return: The provider of this CreateEnvironmentInput.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this CreateEnvironmentInput.

        Name of the cloud service provider for the environment.  # noqa: E501

        :param provider: The provider of this CreateEnvironmentInput.  # noqa: E501
        :type: str
        """
        allowed_values = ["aws", "aws_govcloud", "azure"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def provider_options(self):
        """Gets the provider_options of this CreateEnvironmentInput.  # noqa: E501

        A dictionary of options for the provider.  # noqa: E501

        :return: The provider_options of this CreateEnvironmentInput.  # noqa: E501
        :rtype: ProviderOptions
        """
        return self._provider_options

    @provider_options.setter
    def provider_options(self, provider_options):
        """Sets the provider_options of this CreateEnvironmentInput.

        A dictionary of options for the provider.  # noqa: E501

        :param provider_options: The provider_options of this CreateEnvironmentInput.  # noqa: E501
        :type: ProviderOptions
        """

        self._provider_options = provider_options

    @property
    def compliance_families(self):
        """Gets the compliance_families of this CreateEnvironmentInput.  # noqa: E501

        List of compliance families validated against the environment.  # noqa: E501

        :return: The compliance_families of this CreateEnvironmentInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._compliance_families

    @compliance_families.setter
    def compliance_families(self, compliance_families):
        """Sets the compliance_families of this CreateEnvironmentInput.

        List of compliance families validated against the environment.  # noqa: E501

        :param compliance_families: The compliance_families of this CreateEnvironmentInput.  # noqa: E501
        :type: list[str]
        """

        self._compliance_families = compliance_families

    @property
    def survey_resource_types(self):
        """Gets the survey_resource_types of this CreateEnvironmentInput.  # noqa: E501

        List of resource types to be surveyed.  # noqa: E501

        :return: The survey_resource_types of this CreateEnvironmentInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._survey_resource_types

    @survey_resource_types.setter
    def survey_resource_types(self, survey_resource_types):
        """Sets the survey_resource_types of this CreateEnvironmentInput.

        List of resource types to be surveyed.  # noqa: E501

        :param survey_resource_types: The survey_resource_types of this CreateEnvironmentInput.  # noqa: E501
        :type: list[str]
        """

        self._survey_resource_types = survey_resource_types

    @property
    def remediate_resource_types(self):
        """Gets the remediate_resource_types of this CreateEnvironmentInput.  # noqa: E501

        List of resource types to be remediated if remediation is enabled.  # noqa: E501

        :return: The remediate_resource_types of this CreateEnvironmentInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._remediate_resource_types

    @remediate_resource_types.setter
    def remediate_resource_types(self, remediate_resource_types):
        """Sets the remediate_resource_types of this CreateEnvironmentInput.

        List of resource types to be remediated if remediation is enabled.  # noqa: E501

        :param remediate_resource_types: The remediate_resource_types of this CreateEnvironmentInput.  # noqa: E501
        :type: list[str]
        """

        self._remediate_resource_types = remediate_resource_types

    @property
    def scan_schedule_enabled(self):
        """Gets the scan_schedule_enabled of this CreateEnvironmentInput.  # noqa: E501

        Indicates if the new environment should have scans run on a schedule upon creation.  # noqa: E501

        :return: The scan_schedule_enabled of this CreateEnvironmentInput.  # noqa: E501
        :rtype: bool
        """
        return self._scan_schedule_enabled

    @scan_schedule_enabled.setter
    def scan_schedule_enabled(self, scan_schedule_enabled):
        """Sets the scan_schedule_enabled of this CreateEnvironmentInput.

        Indicates if the new environment should have scans run on a schedule upon creation.  # noqa: E501

        :param scan_schedule_enabled: The scan_schedule_enabled of this CreateEnvironmentInput.  # noqa: E501
        :type: bool
        """

        self._scan_schedule_enabled = scan_schedule_enabled

    @property
    def scan_interval(self):
        """Gets the scan_interval of this CreateEnvironmentInput.  # noqa: E501

        Time in seconds between the end of one scan to the start of the next. Must also set scan_schedule_enabled to true.  # noqa: E501

        :return: The scan_interval of this CreateEnvironmentInput.  # noqa: E501
        :rtype: int
        """
        return self._scan_interval

    @scan_interval.setter
    def scan_interval(self, scan_interval):
        """Sets the scan_interval of this CreateEnvironmentInput.

        Time in seconds between the end of one scan to the start of the next. Must also set scan_schedule_enabled to true.  # noqa: E501

        :param scan_interval: The scan_interval of this CreateEnvironmentInput.  # noqa: E501
        :type: int
        """
        if scan_interval is not None and scan_interval < 300:  # noqa: E501
            raise ValueError("Invalid value for `scan_interval`, must be a value greater than or equal to `300`")  # noqa: E501

        self._scan_interval = scan_interval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateEnvironmentInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
