# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.non_compliant_resource_failed_rules import NonCompliantResourceFailedRules  # noqa: F401,E501


class NonCompliantResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'str',
        'failed_rules': 'list[NonCompliantResourceFailedRules]'
    }

    attribute_map = {
        'resource_id': 'resource_id',
        'failed_rules': 'failed_rules'
    }

    def __init__(self, resource_id=None, failed_rules=None):  # noqa: E501
        """NonCompliantResource - a model defined in Swagger"""  # noqa: E501

        self._resource_id = None
        self._failed_rules = None
        self.discriminator = None

        if resource_id is not None:
            self.resource_id = resource_id
        if failed_rules is not None:
            self.failed_rules = failed_rules

    @property
    def resource_id(self):
        """Gets the resource_id of this NonCompliantResource.  # noqa: E501

        ID of the failing resource.  # noqa: E501

        :return: The resource_id of this NonCompliantResource.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this NonCompliantResource.

        ID of the failing resource.  # noqa: E501

        :param resource_id: The resource_id of this NonCompliantResource.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def failed_rules(self):
        """Gets the failed_rules of this NonCompliantResource.  # noqa: E501

        List of rules and messages the resource violates.  # noqa: E501

        :return: The failed_rules of this NonCompliantResource.  # noqa: E501
        :rtype: list[NonCompliantResourceFailedRules]
        """
        return self._failed_rules

    @failed_rules.setter
    def failed_rules(self, failed_rules):
        """Sets the failed_rules of this NonCompliantResource.

        List of rules and messages the resource violates.  # noqa: E501

        :param failed_rules: The failed_rules of this NonCompliantResource.  # noqa: E501
        :type: list[NonCompliantResourceFailedRules]
        """

        self._failed_rules = failed_rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NonCompliantResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
