# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PermissionsAws(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'policy': 'object',
        'trust_relationship': 'object'
    }

    attribute_map = {
        'policy': 'policy',
        'trust_relationship': 'trust_relationship'
    }

    def __init__(self, policy=None, trust_relationship=None):  # noqa: E501
        """PermissionsAws - a model defined in Swagger"""  # noqa: E501

        self._policy = None
        self._trust_relationship = None
        self.discriminator = None

        if policy is not None:
            self.policy = policy
        if trust_relationship is not None:
            self.trust_relationship = trust_relationship

    @property
    def policy(self):
        """Gets the policy of this PermissionsAws.  # noqa: E501

        JSON policy for surveying and remediating the desired resource types.  # noqa: E501

        :return: The policy of this PermissionsAws.  # noqa: E501
        :rtype: object
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this PermissionsAws.

        JSON policy for surveying and remediating the desired resource types.  # noqa: E501

        :param policy: The policy of this PermissionsAws.  # noqa: E501
        :type: object
        """

        self._policy = policy

    @property
    def trust_relationship(self):
        """Gets the trust_relationship of this PermissionsAws.  # noqa: E501

        JSON trust relationship for IAM role  # noqa: E501

        :return: The trust_relationship of this PermissionsAws.  # noqa: E501
        :rtype: object
        """
        return self._trust_relationship

    @trust_relationship.setter
    def trust_relationship(self, trust_relationship):
        """Sets the trust_relationship of this PermissionsAws.

        JSON trust relationship for IAM role  # noqa: E501

        :param trust_relationship: The trust_relationship of this PermissionsAws.  # noqa: E501
        :type: object
        """

        self._trust_relationship = trust_relationship

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PermissionsAws):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
