# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.attribute import Attribute  # noqa: F401,E501


class ResourceDiff(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'str',
        'resource_type': 'str',
        'change': 'str',
        'attributes': 'list[Attribute]'
    }

    attribute_map = {
        'resource_id': 'resource_id',
        'resource_type': 'resource_type',
        'change': 'change',
        'attributes': 'attributes'
    }

    def __init__(self, resource_id=None, resource_type=None, change=None, attributes=None):  # noqa: E501
        """ResourceDiff - a model defined in Swagger"""  # noqa: E501

        self._resource_id = None
        self._resource_type = None
        self._change = None
        self._attributes = None
        self.discriminator = None

        if resource_id is not None:
            self.resource_id = resource_id
        if resource_type is not None:
            self.resource_type = resource_type
        if change is not None:
            self.change = change
        if attributes is not None:
            self.attributes = attributes

    @property
    def resource_id(self):
        """Gets the resource_id of this ResourceDiff.  # noqa: E501

        ID of the resource given by the provider.  # noqa: E501

        :return: The resource_id of this ResourceDiff.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this ResourceDiff.

        ID of the resource given by the provider.  # noqa: E501

        :param resource_id: The resource_id of this ResourceDiff.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def resource_type(self):
        """Gets the resource_type of this ResourceDiff.  # noqa: E501

        Resource type.  # noqa: E501

        :return: The resource_type of this ResourceDiff.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ResourceDiff.

        Resource type.  # noqa: E501

        :param resource_type: The resource_type of this ResourceDiff.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def change(self):
        """Gets the change of this ResourceDiff.  # noqa: E501

        Type of change which occurred.  # noqa: E501

        :return: The change of this ResourceDiff.  # noqa: E501
        :rtype: str
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this ResourceDiff.

        Type of change which occurred.  # noqa: E501

        :param change: The change of this ResourceDiff.  # noqa: E501
        :type: str
        """
        allowed_values = ["ADDED", "MODIFIED", "REMOVED"]  # noqa: E501
        if change not in allowed_values:
            raise ValueError(
                "Invalid value for `change` ({0}), must be one of {1}"  # noqa: E501
                .format(change, allowed_values)
            )

        self._change = change

    @property
    def attributes(self):
        """Gets the attributes of this ResourceDiff.  # noqa: E501

        Description of the changes to the resource's attributes.  # noqa: E501

        :return: The attributes of this ResourceDiff.  # noqa: E501
        :rtype: list[Attribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ResourceDiff.

        Description of the changes to the resource's attributes.  # noqa: E501

        :param attributes: The attributes of this ResourceDiff.  # noqa: E501
        :type: list[Attribute]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceDiff):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
