# coding: utf-8

"""
    Fugue API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScanWithSummaryResourceTypeErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_type': 'str',
        'error_message': 'str'
    }

    attribute_map = {
        'resource_type': 'resource_type',
        'error_message': 'error_message'
    }

    def __init__(self, resource_type=None, error_message=None):  # noqa: E501
        """ScanWithSummaryResourceTypeErrors - a model defined in Swagger"""  # noqa: E501

        self._resource_type = None
        self._error_message = None
        self.discriminator = None

        self.resource_type = resource_type
        self.error_message = error_message

    @property
    def resource_type(self):
        """Gets the resource_type of this ScanWithSummaryResourceTypeErrors.  # noqa: E501


        :return: The resource_type of this ScanWithSummaryResourceTypeErrors.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ScanWithSummaryResourceTypeErrors.


        :param resource_type: The resource_type of this ScanWithSummaryResourceTypeErrors.  # noqa: E501
        :type: str
        """
        if resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501

        self._resource_type = resource_type

    @property
    def error_message(self):
        """Gets the error_message of this ScanWithSummaryResourceTypeErrors.  # noqa: E501


        :return: The error_message of this ScanWithSummaryResourceTypeErrors.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this ScanWithSummaryResourceTypeErrors.


        :param error_message: The error_message of this ScanWithSummaryResourceTypeErrors.  # noqa: E501
        :type: str
        """
        if error_message is None:
            raise ValueError("Invalid value for `error_message`, must not be `None`")  # noqa: E501

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScanWithSummaryResourceTypeErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
